# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: windows-latest

stages:
- stage: prep
  jobs:
  - job: sdk_and_nuget_download # can't have a space here?????
    displayName: download the most current SDK 
    steps:
    - task: UseDotNet@2
      displayName: get the sdk
      inputs:
        packageType: 'sdk'
        version: '6.x'    
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
        checkLatest: true
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'BookStore'
        organization: 'larry496'
        scannerMode: 'MSBuild'
        projectKey: 'larry496_BookStore'
        projectName: 'BookStore'
    